laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::post('parceiros/imagemUpload', 'ParceirosController@imagemUpload')->name('painel.parceiros.imagem');
        Route::resource('parceiros', 'ParceirosController');
        Route::post('links/imagemUpload', 'LinksController@imagemUpload')->name('painel.links.imagem');
        Route::resource('links', 'LinksController');
        Route::post('artigos/imagemUpload', 'ArtigosController@imagemUpload')->name('painel.artigos.imagem');
		Route::resource('artigos', 'ArtigosController');
		Route::resource('paginas', 'PaginasController');
		Route::resource('chamada-home', 'ChamadaHomeController', ['only' => ['index', 'update']]);
		Route::resource('citacoes', 'CitacoesController');
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });

    // Front-end
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('artigos', 'ArtigosController@index')->name('artigos');
    Route::get('links', 'LinksController@index')->name('links');
    Route::get('parceiros', 'ParceirosController@index')->name('parceiros');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('{pagina_slug}', 'PaginasController@index')->name('pagina');
});

laravel/app/Http/Controllers/Painel/ArtigosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ArtigosRequest;
use App\Http\Requests\ArtigosImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\Artigo;
use App\Models\ArtigosImagem;

class ArtigosController extends Controller
{
    public function index()
    {
        $registros = Artigo::ordenados()->get();
        $artigosImagem = ArtigosImagem::first();

        return view('painel.artigos.index', compact('registros', 'artigosImagem'));
    }

    public function create()
    {
        return view('painel.artigos.create');
    }

    public function store(ArtigosRequest $request)
    {
        try {

            $input = $request->all();
            if ($request->hasFile('arquivo')) $input['arquivo'] = Artigo::uploadArquivo();

            Artigo::create($input);
            return redirect()->route('painel.artigos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Artigo $registro)
    {
        return view('painel.artigos.edit', compact('registro'));
    }

    public function update(ArtigosRequest $request, Artigo $registro)
    {
        try {

            $input = $request->all();
            if ($request->hasFile('arquivo')) $input['arquivo'] = Artigo::uploadArquivo();

            $registro->update($input);
            return redirect()->route('painel.artigos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Artigo $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.artigos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function imagemUpload(ArtigosImagemRequest $request)
    {
        try {

            ArtigosImagem::first()->update([
                'imagem' => ArtigosImagem::uploadImagem()
            ]);

            return back()->with('success', 'Imagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Banner::uploadImagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();
            if (isset($input['imagem'])) $input['imagem'] = Banner::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadaHomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadaHomeRequest;
use App\Http\Controllers\Controller;

use App\Models\ChamadaHome;

class ChamadaHomeController extends Controller
{
    public function index()
    {
        $registro = ChamadaHome::first();

        return view('painel.chamada-home.edit', compact('registro'));
    }

    public function update(ChamadaHomeRequest $request, ChamadaHome $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.chamada-home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CitacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CitacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Citacao;

class CitacoesController extends Controller
{
    public function index()
    {
        $registros = Citacao::ordenados()->get();

        return view('painel.citacoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.citacoes.create');
    }

    public function store(CitacoesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Citacao::uploadImagem();

            Citacao::create($input);
            return redirect()->route('painel.citacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Citacao $registro)
    {
        return view('painel.citacoes.edit', compact('registro'));
    }

    public function update(CitacoesRequest $request, Citacao $registro)
    {
        try {

            $input = $request->all();
            if (isset($input['imagem'])) $input['imagem'] = Citacao::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.citacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Citacao $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.citacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();
            if (isset($input['imagem'])) $input['imagem'] = Contato::uploadImagem();
            if (isset($input['imagem_secundaria_1'])) $input['imagem_secundaria_1'] = Contato::uploadImagemSecundaria(1);
            if (isset($input['imagem_secundaria_2'])) $input['imagem_secundaria_2'] = Contato::uploadImagemSecundaria(2);

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/LinksController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\LinksRequest;
use App\Http\Requests\LinksImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\Link;
use App\Models\LinksImagem;

class LinksController extends Controller
{
    public function index()
    {
        $registros = Link::ordenados()->get();
        $linksImagem = LinksImagem::first();

        return view('painel.links.index', compact('registros', 'linksImagem'));
    }

    public function create()
    {
        return view('painel.links.create');
    }

    public function store(LinksRequest $request)
    {
        try {

            $input = $request->all();

            Link::create($input);
            return redirect()->route('painel.links.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Link $registro)
    {
        return view('painel.links.edit', compact('registro'));
    }

    public function update(LinksRequest $request, Link $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);
            return redirect()->route('painel.links.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Link $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.links.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function imagemUpload(LinksImagemRequest $request)
    {
        try {

            LinksImagem::first()->update([
                'imagem' => LinksImagem::uploadImagem()
            ]);

            return back()->with('success', 'Imagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PaginasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PaginasRequest;
use App\Http\Controllers\Controller;

use App\Models\Pagina;

class PaginasController extends Controller
{
    public function index()
    {
        $registros = Pagina::ordenados()->get();

        return view('painel.paginas.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.paginas.create');
    }

    public function store(PaginasRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Pagina::uploadImagem();

            Pagina::create($input);
            return redirect()->route('painel.paginas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Pagina $registro)
    {
        return view('painel.paginas.edit', compact('registro'));
    }

    public function update(PaginasRequest $request, Pagina $registro)
    {
        try {

            $input = $request->all();
            if (isset($input['imagem'])) $input['imagem'] = Pagina::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.paginas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Pagina $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.paginas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.chamada-home*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.chamada-home.index') }}">Chamada Home</a>
    </li>
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
    <li @if(str_is('painel.citacoes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.citacoes.index') }}">Citações</a>
    </li>
    <li @if(str_is('painel.paginas*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.paginas.index') }}">Páginas</a>
    </li>
	<li @if(str_is('painel.artigos*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.artigos.index') }}">Artigos</a>
	</li>
    <li @if(str_is('painel.links*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.links.index') }}">Links</a>
    </li>
    <li @if(str_is('painel.parceiros*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.parceiros.index') }}">Parceiros</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">ITP</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>